it is resistant to event-injection chrome extension like metamask
kakao/kakao_flutter_sdk pull request #185
Opened 2023-11-14 23:13 UTC by hackartists

Like Metamask, some extensions inject events at the middle in the popup window. And it causes type confliction.

## 설명 (Description)
- Metamask 확장프로그램은 이벤트 injection 이 발생해서, 브라우저 오픈했을때, 첫번째 오는 이벤트가 redirect 에 대한 이벤트가 아닙니다.
- 따라서 이벤트 받는 부분에 대한 로직 수정

### Korean
- [ ] [Contributor 가이드](https://github.com/kakao/kakao_flutter_sdk/wiki/Submitting-Pull-Requests)를 읽고 절차를 모두 진행했습니다.
- [ ] `README.md` 파일과 `CHANGELOG.md` 파일, `pubspec.yaml` 파일을 수정하지 않았습니다.
- [ ] 모든 테스트를 통과했습니다.

### English
- [ ] I read the [Contributor Guide](https://github.com/kakao/kakao_flutter_sdk/wiki/Submitting-Pull-Requests) and followed the process outlined there for submitting PRs.
- [ ] I did not modify the `README.md` nor `CHANGELOG.md` nor the `pubspec.yaml` files.
- [ ] All tests are passing.

2023-11-14 23:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kakao/kakao_flutter_sdk?pullRequest=185) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kakao/kakao_flutter_sdk?pullRequest=185) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kakao/kakao_flutter_sdk?pullRequest=185) it.</sub>

2023-11-15 06:05 UTC, mbkim95 commented
@hackartists 

안녕하세요

우선 kakao_flutter_sdk에 관심가져주셔서 감사합니다.
인지하고 못하고 있던 케이스였는데 이슈 파악 및 수정까지 해주셔서 해당 코드를 반영하려고 합니다. 
그런데 일부 수정이 필요한 부분이 있어서 해당 내용 확인 부탁드리겠습니다.

launchBrowserTab 메서드는 popupOpen 파라미터에 따라서 동작이 달라져야하는데, 현재 작업해주신 코드는 popupOpen이 `false`인 경우에 if문 아래의 코드까지 실행되고 있습니다. 49번줄 `html.window.location.href = finalUri.toString();` 이 실행되면서 페이지 이동이 발생해 별도로 팝업이 열리지 않고 동작하고는 있지만, 코드 유지보수 관점에서 봤을 때, 혹시 모를 오동작의 가능성이 있기 때문에 `popupOpen` 파라미터에 따른 분기를 하는게 좋을 것 같습니다.

또한 메시지 이벤트를 전달받아 `runtimeType` 을 체크해서 동작하도록 구현되어있는데요, 코드가 runtimetype 으로 작성되어있어서 정상적으로 동작하지 못하고 있습니다. 이 부분도 추가로 수정 부탁드려요.
작업해주신 코드 베이스로 아래와 같이 수정해서 머지되는게 좋아보입니다.
```dart
case "launchBrowserTab":
        Map<dynamic, dynamic> args = call.arguments;
        String uri = args["url"];
        bool popupLogin = args[CommonConstants.isPopup];
        final fullUri = Uri.parse(uri);
        Map<String, dynamic> queryParameters =
            Map.from(fullUri.queryParameters);

        html.WindowBase? popupWindow;
        if (popupLogin) {
          queryParameters[CommonConstants.redirectUri] =
              html.window.location.origin;
          final finalUri = fullUri.replace(queryParameters: queryParameters);
          popupWindow =
              html.window.open(finalUri.toString(), "KakaoAccountLogin");
        } else {
          queryParameters[CommonConstants.redirectUri] =
              args[CommonConstants.redirectUri];
          final finalUri = fullUri.replace(queryParameters: queryParameters);
          html.window.location.href = finalUri.toString();
        }

        final msg = await html.window.onMessage.firstWhere((evt) {
          if (evt.data.runtimeType != String) return false;

          return evt.origin ==
              Uri.parse(queryParameters[CommonConstants.redirectUri]).origin;
        });

        popupWindow?.close();
        return msg.data;
```

2023-11-17 04:21 UTC, hackartists commented
@mbkim95 일단 이게 크게 팝업 로그인과 팝업로그인이 아닐때로 나뉘는데, 사실 제가 기존에 팝업로그인이 아닌경우를 여기에서 따로 건드리지 않았던 것은, href 가 고쳐지면 자동으로 리프레시로 가는줄 알고 따로 고쳐두지 않았었는데요. 
아래와 같이 팝업이 아닌 경우에는 리턴을 하는게 낫지 않을까 싶네요?

https://github.com/kakao/kakao_flutter_sdk/pull/185/files#diff-413a4345a3c8a633bcabd6099390da6e0bc8d2286ae4af8decb1d4d3fe28c2ebR45-R52

```
        if (!popupLogin) {
          queryParameters[CommonConstants.redirectUri] =
              args[CommonConstants.redirectUri];
          final finalUri = fullUri.replace(queryParameters: queryParameters);
          html.window.location.href = finalUri.toString();

          return null;
        }
```

한번 검토해보시고, 이 코드로 말씀하신 버그가 모두 픽스되지 않는다면, 제안주신 코드로 적용할게요.

2023-11-17 05:43 UTC, mbkim95 commented
@hackartists 
추가 작업해주신 코드 확인해봤는데, 말씀주신대로 팝업이 아닌 경우에는 곧바로 `return` 해주는게 더 좋네요ㅎㅎ
다만 `handleMethodCall` 메서드가 `Future<dynamic>` 을 반환하도록 되어있다보니 의미없는 `null` 을 리턴하기보다는 아무것도 반환하지 않고 `return` 하는 것이 더 좋을 것 같아요. (동작 상의 유미의한 차이는 없지만 불필요한 값을 리턴 할 필요는 없을 것 같아요)

그리고 이전 댓글에서도 언급했지만 수정이 안된 것 같아서 다시 말씀드리면 `runtimetype` 이 `runtimeType` 으로 수정 부탁드려요. 
컴파일은 성공하지만 런타임에 에러가 발생하고 있어요. (`NoSuchMethodError: 'runtimetype' method not found`)

최종적으로는 아래와 같은 코드가 될 것 같네요
```dart
case "launchBrowserTab":
        Map<dynamic, dynamic> args = call.arguments;
        String uri = args["url"];
        bool popupLogin = args[CommonConstants.isPopup];
        final fullUri = Uri.parse(uri);
        Map<String, dynamic> queryParameters =
            Map.from(fullUri.queryParameters);

        if (!popupLogin) {
          queryParameters[CommonConstants.redirectUri] =
              args[CommonConstants.redirectUri];
          final finalUri = fullUri.replace(queryParameters: queryParameters);
          html.window.location.href = finalUri.toString();
          return;
        }

        queryParameters[CommonConstants.redirectUri] =
            html.window.location.origin;
        final finalUri = fullUri.replace(queryParameters: queryParameters);

        var popupWindow =
            html.window.open(finalUri.toString(), "KakaoAccountLogin");

        final msg = await html.window.onMessage.firstWhere((evt) {
          if (evt.data.runtimeType != String) return false;

          return evt.origin ==
              Uri.parse(queryParameters[CommonConstants.redirectUri]).origin;
        });
        popupWindow.close();
        return msg.data;
```

2023-11-17 06:05 UTC, hackartists commented
@mbkim95 주신 피드백으로 수정했습니다. 다만, 주신 코드에서 popupWindow 는 굳이 var 일 필요는 없어서, void return 만 반영했으니, 참고해주세요~

2023-11-17 06:10 UTC, mbkim95 requested changes

2023-11-17 06:10 UTC, mbkim95 commented on packages/kakao_flutter_sdk_common/lib/src/web/kakao_flutter_sdk_plugin.dart
> +          if (evt.data.runtimetype != String) return false;
`runtimeType`으로 수정 부탁드려요 (런타임에 NoSuchMethodError: 'runtimetype' method not found 에러 발생)

2023-11-21 01:40 UTC, hackartists commented on packages/kakao_flutter_sdk_common/lib/src/web/kakao_flutter_sdk_plugin.dart
> +          if (evt.data.runtimetype != String) return false;
수정했습니다.

2023-11-21 02:00 UTC, merged